name: Contexts
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print context information
        run: |
          echo "actor=${{ github.actor }}"
          echo "run_id=${{ github.run_id }}"
          echo "head_ref=${{ github.head_ref }}"
          echo "workspace=${{ github.workspace }}"
          echo "repository=${{ github.repository }}"
          echo "repository_owner=${{ github.repository_owner }}"
          echo "event=${{ toJSON(github.event) }}"

 